language: julia

os:
  - linux
  - osx

julia:
  - 0.5
  - nightly

matrix:
  allow_failures:
    - julia: nightly

sudo: required

git:
  depth: 9999

notifications:
  email: false

addons:
  apt_packages:
    - gfortran

branches:
  only:
    - master

before_install:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi

script:
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("NLPModels"); Pkg.test("NLPModels"; coverage=true)'

after_success:
  - julia -e 'for pkg in ["Documenter", "JuMP", "ForwardDiff"] Pkg.add(pkg); end'
  - julia -e 'Pkg.clone("https://github.com/JuliaSmoothOptimizers/OptimizationProblems.jl")'
  - julia -e 'cd(Pkg.dir("NLPModels")); include(joinpath("docs", "make.jl"))'
  - julia -e 'cd(Pkg.dir("NLPModels")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
