site_name:        NLPModels.jl
repo_url:         https://github.com/JuliaSmoothOptimizers/NLPModels.jl
site_description: Nonlinear Programming Models
site_author:      JuliaSmoothOptimizers

theme: material

extra:
  palette:
    primary: 'deep orange'
    accent: 'indigo'
  author:
    github: JuliaSmoothOptimizers

extra_css:
  - assets/Documenter.css
  - assets/style.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-MML-AM_HTMLorMML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - codehilite(css_class=code, guess_lang=False)
  - fenced_code
  - mdx_math

docs_dir: 'build'

pages:
  - Home: index.md
  - Models: models.md
  - Tutorial: tutorial.md
  - API: api.md
  - Reference: reference.md
